version: 2
registries:
  boot-cluster-conditionals :
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/boot-cluster-conditionals
    username: x-access-token
    password: ${{ secrets.DEPENDABOT }}   
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
     interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/"
  registries:
     - boot-cluster-conditionals
  schedule:
    interval: daily
  open-pull-requests-limit: 10
