info:
  nais:
    cluster-name: ${nais.cluster.name}
    image-name : ${nais.app.image}
    app-name : ${nais.app.name}
    namespace-name: ${nais.namespace}
sts:
  base-uri: https://security-token-service.dev.adeo.no
joark:
  base-uri: https://dokarkiv-q2.nais.preprod.local
management :
  info:
    java:
       enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      show-details : always
spring:
  mvc:
    log-request-details : true