management :
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    configprops:
      show-values: always
    env:
      additional-keys-to-sanitize: client-jwk,*jwk,*jwks,secret
      show-values: always
    health:
      show-details : always
sts:
  base-uri: https://security-token-service.dev.adeo.no
inntektskomponent:
  base-uri: https://app-q2.adeo.no/inntektskomponenten-ws/rs/
arena:
  base-uri: https://arena-ords-q2.nais.preprod.local/arena/api
arenasoap:
  base-uri: https://arena-q2.adeo.no/arena_ws/services/
  oppgave-uri: https://arena-q2.adeo.no/ail_ws/BehandleArbeidOgAktivitetOppgave_v1
  behandle-sak-og-aktivitet-uri: https://arena-q2.adeo.no/ail_ws/BehandleSakOgAktivitet_v1
  sts:
      url: https://sts-q2.preprod.local/SecurityTokenServiceProvider/