info:
  nais:
    cluster: ${nais.cluster.name}
    image : ${nais.app.image}
    app : ${nais.app.name}
    namespace: ${nais.namespace}

management :
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    env:
      additional-keys-to-sanitize: client-jwk,jwk,jwks
      show-values: always
    health:
      show-details : always
spring:
  mvc:
    log-request-details : true

sts:
  base-uri: https://security-token-service.dev.adeo.no
inntektskomponent:
  base-uri: https://app-q2.adeo.no/inntektskomponenten-ws/rs/
arena:
  base-uri: https://arena-ords-q1.nais.preprod.local/arena/api
arenasoap:
  base-uri: https://arena-q1.adeo.no/arena_ws/services