info:
  nais:
    cluster: ${nais.cluster.name}
    image : ${nais.app.image}
    app : ${nais.app.name}
    namespace: ${nais.namespace}
sts:
  base-uri: https://security-token-service.dev.adeo.no
joark:
  base-uri: https://dokarkiv.dev.intern.nav.no/
inntektskomponent:
  base-uri: https://app-q2.adeo.no/inntektskomponenten-ws/rs
organisasjon:
  base-uri: https://ereg-services-q1.dev.intern.nav.no
management :
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
    health:
      show-details : always
spring:
  mvc:
    log-request-details : true