apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "1001"
  name: aap-fss-proxy
  namespace: aap
  labels:
    team: aap
spec:
  accessPolicy:
    inbound:
      rules:
        - application: aap-soknad-api
  azure:
    application:
      enabled: true
      tenant: { { azure.tenant } }
  tokenx:
    enabled: true
  port: 8080
  cpuThresholdPercentage: 50
  image: {{image}}
  liveness:
    path: /actuator/health/liveness
    initialDelay: 60
  readiness:
    path: /actuator/health/readiness
    initialDelay: 60
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1500m
      memory: 3072Mi
    requests:
      cpu: 250m
      memory: 1536Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/{{ vault.kvPath }}/srvaap-proxy
        mountPath: /var/run/secrets/nais.io/srvaap-proxy
