name: Bygg og deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    bygg:
        permissions:
            contents: write # sumbit dependency-graph
            id-token: write
            packages: write
            actions: read
            checks: write
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.docker-build-push.outputs.image }}
        steps:
            -   name: Sjekk ut kode
                uses: actions/checkout@v7

            -   name: Sett opp Java
                uses: actions/setup-java@v5.7.0
                with:
                    java-version: 25
                    distribution: temurin

            -   name: Sett opp Gradle
                uses: gradle/actions/setup-gradle@v6.3.0
                with:
                    dependency-graph: generate-and-submit
                    gradle-version: wrapper

            -   name: Bygg fatjar
                run: |
                    ./gradlew clean build --continue

            -   name: Bygg og push Docker-image
                id: docker-build-push
                uses: nais/docker-build-push@v0
                with:
                    team: aap

    deploy-dev:
        environment: dev-fss:aap
        name: Deploy til dev-fss
        needs: bygg
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        env:
            PRINT_PAYLOAD: true
            RESOURCE: .deploy/nais.yaml
            CLUSTER: dev-fss
            VARS: .deploy/dev-fss.yaml
            VAR: image=${{needs.bygg.outputs.image}}
        steps:
            -   uses: actions/checkout@v7
            -   uses: nais/login@v0
                id: login
                with:
                    team: aap
            -   uses: nais/deploy/actions/deploy@v2

    deploy-prod:
        if: github.ref == 'refs/heads/main' # bare deploy til prod fra main

        environment: prod-fss:aap
        name: Deploy til prod-fss
        needs: [deploy-dev, bygg]
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        env:
            PRINT_PAYLOAD: true
            RESOURCE: .deploy/nais.yaml
            CLUSTER: prod-fss
            VARS: .deploy/prod-fss.yaml
            VAR: image=${{needs.bygg.outputs.image}}
        steps:
            -   uses: actions/checkout@v7
            -   uses: nais/login@v0
                id: login
                with:
                    team: aap
            -   uses: nais/deploy/actions/deploy@v2

