name: Bygg PR eller branch

on:
  pull_request:
    branches:
      - main

jobs:

  bygg:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v7

      - name: Sett opp Java
        uses: actions/setup-java@v5.7.0
        with:
          java-version: 25
          distribution: temurin

      - name: Sett opp Gradle
        uses: gradle/actions/setup-gradle@v6.3.0
        with:
          gradle-version: wrapper

      - name: Bygg og test
        run: |
          ./gradlew build test
